### ISSUE TITLE
Typo in section Data Types

### ISSUE THREAD

**Issue by cout970** [Mr-Skully/kotlin-quick-guide#1]
First of all, this project is awesome, thanks for your work, I sure it will help other people to start with Kotlin.

I found a small typo in the section [Data Types](https://github.com/Mr-Skully/kotlin-quick-guide/blob/main/README.md#data-types):

`Int numbers can be added to characters, but the reverse is not true.`
```kotlin
val ch = 'a'
val ch1 = ch + 1      // 'b'
val ch2 = 1 + ch      // Error
val ch += 2           // 'c'
```
The last line is syntactically incorrect:
- You cannot create a new variable with a name already used in the same context
- The `+=` operator is compatible with a variable declaration, you need to remove the `val` keyword
- The variable ch is immutable and it cannot be changed by `+=`

I think a better example could be:
```kotlin
var ch = 'a'
val ch1 = ch + 1      // 'b'
val ch2 = 1 + ch      // Error
ch += 2                   // 'c'
```

This is a small typo, but for someone who is starting to program in Kotlin it is very confusing.

**Comment by Mr-Skully** [comment]
You're absolutely right! That was a typo..
Thanks for pointing it out!!😄
